#!/usr/bin/env python3

import shutil
import os.path

files = [
  ("windows-terminal",
   r"C:\Users\tritl\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json"),
  ("vscode",
   r"C:\Users\tritl\AppData\Roaming\Code\User\settings.json")]

def copyToWsl(x):
 (dst,path) = x
 [drive, rest] = path.split(":")
 others = rest.split("\\")
 src = os.path.join("/mnt", drive.lower(), *others)
 print(f"Copying {src} to {dst}")
 shutil.copy(src, dst)

if __name__=='__main__':
    (list(map(copyToWsl, files)))

