#!/bin/zsh

#empty='⠀'
local batstat=$(cat /sys/class/power_supply/BAT1/status)
local cap=$(cat /sys/class/power_supply/BAT1/capacity)
case $batstat in
    "Charging")
        echo "⠀ $cap%"
        echo " "
        ;;
    "Discharging")
        echo "⠀ $cap%"
        test $cap -gt 24 && echo "#FFFF00" && exit 0
        test $cap -lt 5 && exit 33
        echo "#FF0000"
        exit 0
        ;;
    "Full")
        echo "⠀"
        echo " "
        ;;
    *)
        echo "⠀"
        echo "#FF0000"
        exit 33
        ;;
esac

# The default
echo "#00FF00"
exit 0
