#!/bin/zsh

local currentGPU=$(prime-select query)
local color="#FF0000"
local temp="?"
local switchto=""
local tempPost="°C"

if [[ $currentGPU =~ nvidia ]]; then
    color="#99FF99"
    temp=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader)
    switchto="intel"
else
    temp=$(sensors | grep Physical | awk '{print $4}' | tr '.' "\n" | head -n 1 | tr "+" "\n" | tail -n 1)
    color="#9999FF"
    switchto="nvidia"
fi



[[ $temp -gt 70 ]] && color="#FFFF00"
[[ $temp -gt 80 ]] && color="#FF0000"

echo "$currentGPU $temp$tempPost"
echo "$temp$tempPost"
echo "$color"
if [[ $BLOCK_BUTTON -gt 1 ]]; then
    gksudo prime-select $switchto
fi
