#!/bin/zsh


printSizeHumanReadable() {
  typeset -F 2 size
  size="$1"+0.00001
  local extension
  extension=('B' 'K' 'M' 'G' 'T' 'P' 'E' 'Z' 'Y')
  local index=1

  # if the base is not Bytes
  if [[ -n $2 ]]; then
    for idx in "${extension[@]}"; do
      if [[ "$2" == "$idx" ]]; then
        break
      fi
      index=$(( index + 1 ))
    done
  fi

  while (( (size / 1024) > 0.1 )); do
    size=$(( size / 1024 ))
    index=$(( index + 1 ))
  done

  echo "$size${extension[$index]}"
}

local loadavg1min=$(grep -o "[0-9.]*" /proc/loadavg | head -n 1)
local ramfree=$(grep -o -E "MemFree:\s+[0-9]+" /proc/meminfo | grep -o "[0-9]*")
local swap_free=$(grep -o -E "SwapFree:\s+[0-9]+" /proc/meminfo | grep -o "[0-9]*")


local swap_total=$(grep -o -E "SwapTotal:\s+[0-9]+" /proc/meminfo | grep -o "[0-9]*")
local swap_used=$(( swap_total - swap_free ))

local hramfree=$(printSizeHumanReadable $ramfree "K")
local hswap_free=''
if [[ $swap_used -gt 0 ]]; then
    hswap_free=$(printSizeHumanReadable $swap_free "K")
    hswap_free=" $hswap_free"
fi
local color="#FFFFFF"
[[ loadavg1min -gt 0.5 ]] && color="#00FF00"
[[ loadavg1min -gt 1 ]] && color="#FFFF00"
[[ loadavg1min -gt 2 ]] && color="#FF0000"

echo "$loadavg1min $hramfree$hswap_free"
echo "$loadavg1min"
echo "$color"
if [[ $BLOCK_BUTTON -gt 1 ]]; then
    xterm  -class 'I3FloatingEnableToMouse' -e '/usr/bin/htop'
fi
