#!/bin/zsh
if [[ $BLOCK_BUTTON -gt 0 ]]; then
    spotify
    i3-msg -t command '[urgent="latest" class="Spotify"] focus'
fi
#local songname=$(xprop -name "Spotify Premium - Linux Preview" _NET_WM_ICON_NAME | cut -d "\"" -f 2| cut -d "-" -f 2 )

local spotifystr="$(xprop -name "Spotify Premium - Linux Preview" _NET_WM_ICON_NAME )"
local song="$(xprop -name "Spotify Premium - Linux Preview" _NET_WM_ICON_NAME|cut -d "\"" -f 2  | cut --characters="11-" )"
if [[ -n $song ]]; then
    echo " $song" 
else
    echo ""
fi
echo " "
echo "#2ebd59"
