#!/bin/bash
# USERID=`id -u `
# if test -e /tmp/emacs$USERID/server
# then
# 	echo "Ready."
# else
# 	echo "Starting server."
# 	/etc/init.d/emacs start
#         while [ ! -e "/tmp/emacs$USERID/server" ] ; do sleep 1 ; done
# fi

emacsclient -c  $* -n --alternate-editor /Applications/Emacs.app/Contents/MacOS/Emacs  & disown
