#!/bin/bash

docker ps -a | grep "$@" | awk '{print $1}' | xargs docker inspect | grep "IPAddress"  | awk 'match($0, /[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/){print substr($0,RSTART,RLENGTH)}' | xargs  sh -c 'ssh root@$@ < /dev/tty' ssh
