- name: Tmux
  hosts: 127.0.0.1
  connection: local
  tasks:
      - name: install tmux
        apt: name=tmux state=present
      - name: install powerline
        command: pip install --user git+git://github.com/Lokaltog/powerline
      - name: mk fonts dir
        file: dest={{ansible_env.HOME}}/.fonts state=directory
      - name: install powerline-fonts
        git: repo=https://github.com/Lokaltog/powerline-fonts
            dest={{ansible_env.HOME}}/powerline-fonts
      - name: get patched powerline font
        get_url: url=https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf
                 dest={{ansible_env.HOME}}/.fonts/PowerlineSymbols.otf
      - name: patch font
        command: fc-cache -vf {{ansible_env.HOME}}/.fonts/
      - name: mk fontsconfig dir
        file: dest={{ansible_env.HOME}}/.config/fontconfig/conf.d/ state=directory
      - name: get fontconfig
        get_url: url=https://raw.githubusercontent.com/Lokaltog/powerline/develop/font/10-powerline-symbols.conf
                 dest={{ansible_env.HOME}}/.config/fontconfig/conf.d/
      - name: add terminus to fontconfig file
        replace: dest={{ansible_env.HOME}}/.config/fontconfig/conf.d/10-powerline-symbols.conf regexp='Bitstream Vera Sans Mono' replace='Terminus'
      - include: tasks/stow.yml tostow=tmux

