- name: Vim
  hosts: 127.0.0.1
  connection: local
  tasks:
      - include: tasks/stow.yml tostow=vim
      - name: install vim
        apt: name=vim-gtk state=present
      - name: install vundle
        git: repo=https://github.com/gmarik/Vundle.vim.git
             dest={{ansible_env.HOME}}/.vim/bundle/Vundle.vim
      - name: install vim plugins
        command: gvim +PluginInstall +qall

      - name: install you complete me dep cmake
        apt: name=cmake state=present

      - name: install you complete me dep build-essentials
        apt: name=build-essentials state=present
      - name: install you complete me dep python-dev
        apt: name=python-dev state=present
      - name: compile YouCompleteMe
        command: chdir={{ansible_env.HOME}}/.vim/bundle/YouCompleteMe ./install.sh --clang-completer
